# Generated by Django 2.2.5 on 2019-09-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20190930_1721'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=111111, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
            preserve_default=False,
        ),
    ]
