# Generated by Django 2.2.5 on 2019-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20190930_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_account',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
