# Generated by Django 2.2.5 on 2019-09-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20190930_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredSellers',
            fields=[
                ('seller_account', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
